services:
  - type: web
    name: cobli-email-validator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
